// error handling

try{
    console.log(a);
}catch(err){
    console.error("There was an error",err.message);
}